-- The placeholder job-role baseline that used to live here (10 fake generic
-- roles: GEN, ELEC, RIG, ...) is gone — `scripts/seed-catalog.mjs` now seeds
-- the real 52-role GCC Lab Distribution/Transmission matrix (plus the real
-- 43-course catalog, prerequisites, and regional pricing) against any real
-- Supabase project. Run it after every fresh `supabase db reset` / new
-- environment's `db push`:
--
--   DATABASE_URL=<connection string> node scripts/seed-catalog.mjs
--
-- Kept as a separate script rather than inlined here (unlike the old
-- placeholder) because job-role eligibility resolution needs real
-- title-matching logic across two categories, not a flat SQL insert.
